### ISSUE TITLE
Issue with PDI 6

### ISSUE THREAD

**Issue by CosmicMac** [mattyb149/load-text-from-file-plugin#2]
Hi Matthew,

With PDI 6.0.1, Windows Seven and Java 8 64:

```
Load text from file.0 - ERROR (version 6.0.1.0-386, build 1 from 2015-12-03 11.37.25 by buildguy) : Unexpected error
Load text from file.0 - ERROR (version 6.0.1.0-386, build 1 from 2015-12-03 11.37.25 by buildguy) : java.lang.NoSuchMethodError: org.pentaho.di.core.fileinput.FileInputList.getFile(I)Lorg/apache/commons/vfs/FileObject;
Load text from file.0 -     at org.pentaho.di.trans.steps.loadtextfromfile.LoadTextFromFile.openNextFile(LoadTextFromFile.java:135)
Load text from file.0 -     at org.pentaho.di.trans.steps.loadtextfromfile.LoadTextFromFile.getOneRow(LoadTextFromFile.java:324)
Load text from file.0 -     at org.pentaho.di.trans.steps.loadtextfromfile.LoadTextFromFile.processRow(LoadTextFromFile.java:199)
Load text from file.0 -     at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
Load text from file.0 -     at java.lang.Thread.run(Unknown Source)
```

Cheers,

CM

**Comment by codek** [comment]
I can confirm I also have this issue, probably caused by the vfs changes in 6.x?

java.lang.NoSuchMethodError: org.pentaho.di.core.fileinput.FileInputList.getFile(I)Lorg/apache/commons/vfs/FileObject;
        at org.pentaho.di.trans.steps.loadtextfromfile.LoadTextFromFile.openNextFile(LoadTextFromFile.java:135)
        at org.pentaho.di.trans.steps.loadtextfromfile.LoadTextFromFile.getOneRow(LoadTextFromFile.java:324)
        at org.pentaho.di.trans.steps.loadtextfromfile.LoadTextFromFile.processRow(LoadTextFromFile.java:199)
        at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
        at java.lang.Thread.run(Thread.java:745)

**Comment by codek** [comment]
I've issued a pull request to fix this.

it will break it for pdi5 though, hmm. not sure how best that should be handled.  Not sure if marketplace metadata can have different jars for different versions.

I also changed to 6.1-SNAPSHOT because for some reason the dependencies were not resolving for TRUNK-SNAPSHOT today.

**Comment by andresitovil** [comment]
is there any update/plan to fix this. If not, did you find any workaround to get it working on PDI 6.X?

**Comment by codek** [comment]
The author no longer works for pentaho so I don't see anything changing. Just apply the patch from my pr and all will work won't it?

**Comment by andresitovil** [comment]
What patch? I didn't see any... Is there a further version different than the one which is available in the marketplace?
